services:
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
     - postgres_data:/var/lib/postgresql/data
    env_file:
      - src/.env   
    ports:
      - "5432:5432"

  django:
    build: .
    restart: always
    command: ["python3", "manage.py", "runserver", "0:8000"]
    ports:
     - "8000:8000"
    depends_on:
     - postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - src/.env   
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      # слева внешний мир, справа мир контейнеров


volumes:
  postgres_data:
  pgadmin_data:
