services:
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
     - postgres_data:/var/lib/postgresql/data
    env_file:
      - src/.env   
    ports:
      - "5432:5432"

  django:
    build: .
    restart: always
    command: ["gunicorn", "config.wsgi", "-b", "0:8000", "--workers", "1"]
    volumes:
      - django_staticfiles:/app/staticfiles/  
    depends_on:
     - postgres
     
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - src/.env   
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      # слева внешний мир, справа мир контейнеров

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - django_staticfiles:/home/app/web/staticfiles/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  pgadmin_data:
  django_staticfiles:

